V1.0.0 utils
eastgenomics/panel_ops pull request #27
Opened 2021-02-03 15:51 UTC by Yu-jinKim

2021-02-03 15:51 UTC, pep8speaks commented
Hello @Yu-jinKim! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`ops/utils.py`](https://github.com/eastgenomics/panel_ops/blob/f6728572c6c8a52cd40cf5f6febebb62ba807af6/ops/utils.py):

> [Line 203:80](https://github.com/eastgenomics/panel_ops/blob/f6728572c6c8a52cd40cf5f6febebb62ba807af6/ops/utils.py#L203): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 205:80](https://github.com/eastgenomics/panel_ops/blob/f6728572c6c8a52cd40cf5f6febebb62ba807af6/ops/utils.py#L205): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 262:78](https://github.com/eastgenomics/panel_ops/blob/f6728572c6c8a52cd40cf5f6febebb62ba807af6/ops/utils.py#L262): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 329:80](https://github.com/eastgenomics/panel_ops/blob/f6728572c6c8a52cd40cf5f6febebb62ba807af6/ops/utils.py#L329): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 331:80](https://github.com/eastgenomics/panel_ops/blob/f6728572c6c8a52cd40cf5f6febebb62ba807af6/ops/utils.py#L331): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 335:80](https://github.com/eastgenomics/panel_ops/blob/f6728572c6c8a52cd40cf5f6febebb62ba807af6/ops/utils.py#L335): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 454:80](https://github.com/eastgenomics/panel_ops/blob/f6728572c6c8a52cd40cf5f6febebb62ba807af6/ops/utils.py#L454): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 455:80](https://github.com/eastgenomics/panel_ops/blob/f6728572c6c8a52cd40cf5f6febebb62ba807af6/ops/utils.py#L455): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 456:80](https://github.com/eastgenomics/panel_ops/blob/f6728572c6c8a52cd40cf5f6febebb62ba807af6/ops/utils.py#L456): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 626:80](https://github.com/eastgenomics/panel_ops/blob/f6728572c6c8a52cd40cf5f6febebb62ba807af6/ops/utils.py#L626): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 627:80](https://github.com/eastgenomics/panel_ops/blob/f6728572c6c8a52cd40cf5f6febebb62ba807af6/ops/utils.py#L627): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (93 > 79 characters)
> [Line 628:80](https://github.com/eastgenomics/panel_ops/blob/f6728572c6c8a52cd40cf5f6febebb62ba807af6/ops/utils.py#L628): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 1047:75](https://github.com/eastgenomics/panel_ops/blob/f6728572c6c8a52cd40cf5f6febebb62ba807af6/ops/utils.py#L1047): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 1116:80](https://github.com/eastgenomics/panel_ops/blob/f6728572c6c8a52cd40cf5f6febebb62ba807af6/ops/utils.py#L1116): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 1119:80](https://github.com/eastgenomics/panel_ops/blob/f6728572c6c8a52cd40cf5f6febebb62ba807af6/ops/utils.py#L1119): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)

2021-02-04 13:35 UTC, jethror1 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/27)* status: 0 of 1 files reviewed, 20 unresolved discussions (waiting on @mattgarner and @Yu-jinKim)

___
*[ops/utils.py, line 91 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSgboaBBMJt8WYg2i4y:-MSgboaBBMJt8WYg2i4z:b-bl2a48) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L91)):*
> ```Python
> 
>     Returns:
>         dict: Dict of all panels in panelapp
> ```

it's not all panels in panelapp?
___
*[ops/utils.py, line 154 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSgcP1Y8KaAuABRXDsJ:-MSgcP1Y8KaAuABRXDsK:b2jj6ku) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L154)):*
> ```Python
> 
>     Returns:
>         dict: Dict of gene2transcripts2exons
> ```

quality naming
___
*[ops/utils.py, line 175 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSgcVuaCYHQNPtfaNg8:-MSgcVuaCYHQNPtfaNg9:b-xcxxdx) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L175)):*
> ```Python
>             info_dict = {}
> 
>             # skip lines where the entity type is gene, UTR, CDS
> ```

is gene meant to be in the list or not in the comment?
___
*[ops/utils.py, line 256 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSge1Bh8O6oLVX5pyFE:-MSge1Bh8O6oLVX5pyFF:b-p5a8l1) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L256)):*
> ```Python
>             if nirvana_data[nirvana_tx]["canonical"] is True:
>                 transcript_data[base_nirvana_tx]["canonical"] = True
>             else:
> ```

else not required as all set to False in previous line
___
*[ops/utils.py, line 267 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSgdoxVA3T0VXA2jiNH:-MSgdoxVA3T0VXA2jiNI:bbzlszk) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L267)):*
> ```Python
>                         transcript_data[base_nirvana_tx]["clinical"] = True
>             else:
>                 # if it's not present in hgmd the canonical transcript because
> ```

comment doesn't make sense
___
*[ops/utils.py, line 369 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSgfPh_7WtLaI8ENo_D:-MSgfPh_7WtLaI8ENo_E:b-a962ut) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L369)):*
> ```Python
>                     else:
>                         # we have the index of the line so we can automatically
>                         # get the header and use it has a subkey in the dict
> ```

typo: ~~h~~as
___
*[ops/utils.py, line 377 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSghqXkBrIXa7OtRoxj:-MSghqXkBrIXa7OtRoxk:bw1ifqd) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L377)):*
> ```Python
>                 alias_symbols = line[alias_index].strip("\"").split("|")
>                 prev_symbols = line[prev_index].strip("\"").split("|")
> ```

will alias or prev symbols ever be none? (i.e. if they aren't present and there's nothing to split), if so it might break on the for loops beneath with NoneTypes
___
*[ops/utils.py, line 413 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSgiR286Gpdt5E9oED7:-MSgiR286Gpdt5E9oED8:bwulstw) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L413)):*
> ```Python
>         for i, ele in enumerate(headers)
>         if ele == header_name
>     ][0]
> ```

could the header not be present in headers and break on 0 index?
___
*[ops/utils.py, line 423 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSgmZbCBmo4yjR1GuAx:-MSgmZbCBmo4yjR1GuAy:b-tbzeoc) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L423)):*
> ```Python
>     Args:
>         dump_folder (list): Folder(s) containing the panels
>         hgmd_dict (dict): Dict of HGMD parsed data
> ```

args dont match
___
*[ops/utils.py, line 516 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSgnwon7qIE54HQTYFl:-MSgnwon7qIE54HQTYFm:bbjtkiv) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L516)):*
> ```Python
> 
>     xls = xlrd.open_workbook(file)
>     sheet_with_tests = xls.sheet_by_name("R&ID indications")
> ```

what do you bet they change the sheet name with no warning?
___
*[ops/utils.py, line 525 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSgp4ew4BCbJ6dpEaJe:-MSgp4ew4BCbJ6dpEaJf:bt0x4e8) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L525)):*
> ```Python
>                 ci_id, ci, criteria, test_code,
>                 targets, method, clinical_group, comment
>             ) = sheet_with_tests.row_values(row)
> ```

thinking more generally is it likely that this will change regularly and they could change the structure of the file (i.e. move/rename columns)? Might be good to have a function to sense check the file before ending up with a mess if change it
___
*[ops/utils.py, line 535 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSgonQz9kAvJalUdA21:-MSgonQz9kAvJalUdA22:b-jkjmtz) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L535)):*
> ```Python
>             test_code = test_code.strip()
> 
>             if "panel" in method or "WES" in method or "Single gene" in method:
> ```

`if any(x in method for x in my_terms)` is nicer for checking multiple existence
___
*[ops/utils.py, line 546 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSgpPfaDpYNlx1crkfK:-MSgpPfaDpYNlx1crkfL:b2ni0j2) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L546)):*
> ```Python
> def clean_targets(clinind_data: dict):
>     """ Replace the methods from the XLS to abbreviation:
>     WES and co -> P
> ```

co?
___
*[ops/utils.py, line 591 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSgqCtT3vOr-3rKv51o:-MSgqCtT3vOr-3rKv51p:b-599qa) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L591)):*
> ```Python
>             indiv_target = indiv_target.strip()
> 
>             if "Relevant" not in indiv_target:
> ```

will this _always_ be capitalised? might be worth an upper/lower on both
___
*[ops/utils.py, line 618 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSgr0nY1hCCcvFdvZ8-:-MSgr0nY1hCCcvFdvZ80:b57qffm) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L618)):*
> ```Python
>                         )
>                     else:
>                         # only case where this happens is a
> ```

maybe log this somewhere to check afterwards
___
*[ops/utils.py, line 730 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSgsgw_5pa2--sgxUuS:-MSgsgw_5pa2--sgxUuT:b-asknvh) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L730)):*
> ```Python
>     paneltype_json = []
> 
>     for choice_id, choice in enumerate(panel_types, pk+1):
> ```

why `pk+1`?
___
*[ops/utils.py, line 784 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSgtgS19cITA4ru10W2:-MSgtdnC6CcPmK4Kuwi5:br7ywkh) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L784)):*
> ```
> object_to_return != []
> ```
is this needed? isn't it caught by the `== 1`?
___
*[ops/utils.py, line 875 at [...]

2021-02-09 18:37 UTC, jethror1 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/27)* status: 0 of 1 files reviewed, 21 unresolved discussions (waiting on @mattgarner and @Yu-jinKim)

___
*[ops/utils.py, line 33 at r3](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MT74CVQA9SDWUmFj34F:-MT74CVQA9SDWUmFj34G:b40olet) ([raw file](https://github.com/eastgenomics/panel_ops/blob/633701571fc63602d42f23f98b892005e92281c8/ops/utils.py#L33)):*
> ```Python
> 
> 
> def get_new_output_folder(output_dump: str, output_suffix: str = ""):
> ```

feel like a function that creates something should be named with `create` or `make`, get seems wrong as you use get for query functions etc.


<!-- Sent from Reviewable.io -->

2021-03-02 09:32 UTC, Yu-jinKim reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/27)* status: 0 of 1 files reviewed, 20 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[ops/utils.py, line 91 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSgboaBBMJt8WYg2i4y:-MTAao1k31EOTNkbQB-y:b-qhwfop) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L91)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

it's not all panels in panelapp?
</blockquote></details>

not even sure this function is used anymore
___
*[ops/utils.py, line 154 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSgcP1Y8KaAuABRXDsJ:-MTAaiZY7B3Ata8_G7YC:b-hjtzwf) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L154)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

quality naming
</blockquote></details>

well couldn't find anything better + that naming is wrong now
___
*[ops/utils.py, line 175 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSgcVuaCYHQNPtfaNg8:-MTAaseZ9gauQ9rK8kd7:b-45lhwc) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L175)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

is gene meant to be in the list or not in the comment?
</blockquote></details>

shouldn't be in comment
___
*[ops/utils.py, line 256 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSge1Bh8O6oLVX5pyFE:-MTAb1gv1ZbOD7PWbNzK:b-5tg3ow) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L256)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

else not required as all set to False in previous line
</blockquote></details>

confused x 2
___
*[ops/utils.py, line 267 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSgdoxVA3T0VXA2jiNH:-MTAb0ev82H17Oz3_eV1:bqlrt2e) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L267)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

comment doesn't make sense
</blockquote></details>

confused
___
*[ops/utils.py, line 369 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSgfPh_7WtLaI8ENo_D:-MUmGsl03havAC4irj4v:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L369)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

typo: ~~h~~as
</blockquote></details>

Done.
___
*[ops/utils.py, line 377 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSghqXkBrIXa7OtRoxj:-MTAbDc-3KCly4an71EP:b-t26a7) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L377)):*
>>> s = ""
>>> s.split("|")
['']
I'm parsing a file so no field is going to be None per se
___
*[ops/utils.py, line 413 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSgiR286Gpdt5E9oED7:-MTAbHz26urNlvawG2ND:bw3bioz) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L413)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

could the header not be present in headers and break on 0 index?
</blockquote></details>

The headers i gathered should always be present
___
*[ops/utils.py, line 423 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSgmZbCBmo4yjR1GuAx:-MTAbgQN-3co7A4sxWtC:bote51m) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L423)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

args dont match
</blockquote></details>

must have forgotten about it
___
*[ops/utils.py, line 516 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSgnwon7qIE54HQTYFl:-MTAbloQCiRpI2AbUjnz:b-fvkiso) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L516)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

what do you bet they change the sheet name with no warning?
</blockquote></details>

everything in test_directory is subject to change
___
*[ops/utils.py, line 525 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSgp4ew4BCbJ6dpEaJe:-MTAc1Vt0A8rKUlXnqbB:bojzpw7) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L525)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

thinking more generally is it likely that this will change regularly and they could change the structure of the file (i.e. move/rename columns)? Might be good to have a function to sense check the file before ending up with a mess if change it
</blockquote></details>

i think a better thing to have would be to have a dedicated git for parsing the nightmare that is going to be the test directory
___
*[ops/utils.py, line 535 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSgonQz9kAvJalUdA21:-MTAcLTO8SF7DQVwmEI3:bb74x83) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L535)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

`if any(x in method for x in my_terms)` is nicer for checking multiple existence
</blockquote></details>

True
___
*[ops/utils.py, line 546 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSgpPfaDpYNlx1crkfK:-MTAcMe65vMxwGJCA5k2:b-sbb4wg) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L546)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

co?
</blockquote></details>

don't you have co as an abbreviation of company?
___
*[ops/utils.py, line 591 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSgqCtT3vOr-3rKv51o:-MTAcVfu7yUpJRefUiQT:bb7pcsz) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L591)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

will this _always_ be capitalised? might be worth an upper/lower on both
</blockquote></details>

true
___
*[ops/utils.py, line 618 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSgr0nY1hCCcvFdvZ8-:-MTAci-E-pdqedyScDAt:b-tn0f53) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L618)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

maybe log this somewhere to check afterwards
</blockquote></details>

fair point
___
*[ops/utils.py, line 730 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSgsgw_5pa2--sgxUuS:-MTAcn7r0Qw_JjMeRBNn:b-16pdv2) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L730)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

why `pk+1`?
</blockquote></details>

pk starts at 0
___
*[ops/utils.py, line 784 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSgtgS19cITA4ru10W2:-MUmGx59A2pR6at2GTrn:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L784)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

> ```
> object_to_return != []
> ```
is this needed? isn't it caught by the `== 1`?
</blockquote></details>

Done.
___
*[ops/utils.py, line 875 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSguVQsDEpv8BbLryfN:-MUmGxOHCfRk2JF7hj5I:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d808056 [...]

2021-03-02 09:48 UTC, jethror1 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/27)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @jethror1, @mattgarner, and @Yu-jinKim)

___
*[ops/utils.py, line 91 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSgboaBBMJt8WYg2i4y:-MUmJUuo85Giq98YErtY:b-11tzgq) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L91)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

not even sure this function is used anymore
</blockquote></details>

probably should check and remove if not
___
*[ops/utils.py, line 256 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSge1Bh8O6oLVX5pyFE:-MUmJekx0EtN9KRGzqq3:bnj7hl0) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L256)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

confused x 2
</blockquote></details>

same as above
___
*[ops/utils.py, line 267 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSgdoxVA3T0VXA2jiNH:-MUmJcbk-OM5-LJjkocr:b-ai98eo) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L267)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

confused
</blockquote></details>

I think you made changes and this went
___
*[ops/utils.py, line 525 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSgp4ew4BCbJ6dpEaJe:-MUmJvgp0Bgy49ggfgzs:b28a595) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L525)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

i think a better thing to have would be to have a dedicated git for parsing the nightmare that is going to be the test directory
</blockquote></details>

true, then it could have lots of checks to make sure they haven't changed anything and clean everything up. Sounds like a good python exercise for someone....
___
*[ops/utils.py, line 546 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSgpPfaDpYNlx1crkfK:-MUmK9ZG3YuqbgPCJhCk:bz392kj) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L546)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

don't you have co as an abbreviation of company?
</blockquote></details>

sure but out of context it doesn't make sense, co in the context of WES makes you think of genetics terms.  also why is the word company in there??


<!-- Sent from Reviewable.io -->

2021-03-02 11:55 UTC, Yu-jinKim reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/27)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[ops/utils.py, line 91 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSgboaBBMJt8WYg2i4y:-MUmVnmI-zAwWOMQadCg:b-hfpv0l) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L91)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

probably should check and remove if not
</blockquote></details>

removed
___
*[ops/utils.py, line 256 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSge1Bh8O6oLVX5pyFE:-MUmmkgy3r3V5tO2sHyt:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L256)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[ops/utils.py, line 267 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSgdoxVA3T0VXA2jiNH:-MUmmkJNDlDSiRmpQqoZ:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L267)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

I think you made changes and this went
</blockquote></details>

Done.
___
*[ops/utils.py, line 525 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSgp4ew4BCbJ6dpEaJe:-MUmU9zd9cq2sDpGFA_f:b-raggl) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L525)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

true, then it could have lots of checks to make sure they haven't changed anything and clean everything up. Sounds like a good python exercise for someone....
</blockquote></details>

not going to make changes for this release for now then, we can revisit this when the test directory changes
___
*[ops/utils.py, line 546 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MSgpPfaDpYNlx1crkfK:-MUmULFs5fgdW-YVOtTp:bop3pbc) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L546)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

sure but out of context it doesn't make sense, co in the context of WES makes you think of genetics terms.  also why is the word company in there??
</blockquote></details>

why not? :D (removing it)
___
*[ops/utils.py, line 1070 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MShEVY2EtZitZoerf2s:-MUmiBdjELMGDAcWJ8f8:b9vcp5x) ([raw file](https://github.com/eastgenomics/panel_ops/blob/d4954f35747d80805624700d2b4ad3e1441508fc/ops/utils.py#L1070)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

Done.
</blockquote></details>

If i do `if not gemini_name:` it doens't work


<!-- Sent from Reviewable.io -->

2021-03-04 08:13 UTC, mattgarner requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/27)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @Yu-jinKim)

___
*[ops/utils.py, line 41 at r4](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MUTRnaQ8Musa4_ub-Rx:-MUTRnaQ8Musa4_ub-Ry:b-a80d85) ([raw file](https://github.com/eastgenomics/panel_ops/blob/4d076c16f9e7e7e7197cbb6e881102f2f681e88d/ops/utils.py#L41)):*
> ```
> output
> ```
output folder
___
*[ops/utils.py, line 108 at r4](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MUTY_481OVx9SlrEA4C:-MUTY_493b-1sahjdabi:bl46gai) ([raw file](https://github.com/eastgenomics/panel_ops/blob/4d076c16f9e7e7e7197cbb6e881102f2f681e88d/ops/utils.py#L108)):*
> ```
> of panelapp_id
> ```
of GMS panels panelapp_id
(for consistency with docstrings of related functions)
___
*[ops/utils.py, line 187 at r4](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MUTZMLU-i56OLVkd2-d:-MUTZMLU-i56OLVkd2-e:bgegpai) ([raw file](https://github.com/eastgenomics/panel_ops/blob/4d076c16f9e7e7e7197cbb6e881102f2f681e88d/ops/utils.py#L187)):*
> ```
>             gene, transcript = line.strip().split()
>             g2t[gene] = transcript
> ```
Could we add a quick check to avoid overwriting existing values in the dict if the same gene is present twice in g2t? Would be better to just error/fail
e.g.
```
GeneA  NM_00001.1
GeneA  NM_00002.2
```
___
*[ops/utils.py, line 199 at r4](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MUT_2wuBo3yAAVaH-o0:-MUT_2wv-acwc8yPEzAe:b-mabazc) ([raw file](https://github.com/eastgenomics/panel_ops/blob/4d076c16f9e7e7e7197cbb6e881102f2f681e88d/ops/utils.py#L199)):*
> ```
> file
> ```
filepath
___
*[ops/utils.py, line 325 at r4](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MUTaWq29BE_m-GFLR3b:-MUTaWq34i21R3ckQjdH:blucrp) ([raw file](https://github.com/eastgenomics/panel_ops/blob/4d076c16f9e7e7e7197cbb6e881102f2f681e88d/ops/utils.py#L325)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
>     if gene_symbol in hgnc_data:
>         hgnc_id = hgnc_data[gene_symbol]["hgnc_id"]
>         ensg_id = hgnc_data[gene_symbol]["ensg_id"]
>     elif gene_symbol in alias_data:
>         hgnc_id = alias_data[gene_symbol]["hgnc_id"]
>         ensg_id = alias_data[gene_symbol]["ensg_id"]
>     elif gene_symbol in prev_data:
>         hgnc_id = prev_data[gene_symbol]["hgnc_id"]
>         ensg_id = prev_data[gene_symbol]["ensg_id"]
> ```
</details>

If the query symbol is in multiple data (hgnc/alias/prev) can you be certain that you are selecting the intended symbol?
___
*[ops/utils.py, line 426 at r5](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MUwHprqBo7ketU4Xo9X:-MUwHprr9yw01wHi0YRM:b-j91i2h) ([raw file](https://github.com/eastgenomics/panel_ops/blob/1405f0e957eb1da3a36101d436f6f5bbd5a46dea/ops/utils.py#L426)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>     return [
>         i
>         for i, ele in enumerate(headers)
>         if ele == header_name
>     ][0]
> ```
</details>

or headers.index(header_name)


<!-- Sent from Reviewable.io -->

2021-03-09 09:48 UTC, Yu-jinKim reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/27)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @mattgarner)

___
*[ops/utils.py, line 41 at r4](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MUTRnaQ8Musa4_ub-Rx:-MVLMm0M5UGc38D7XzQa:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/4d076c16f9e7e7e7197cbb6e881102f2f681e88d/ops/utils.py#L41)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> output
> ```
output folder
</blockquote></details>

Done.
___
*[ops/utils.py, line 108 at r4](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MUTY_481OVx9SlrEA4C:-MVLMmhl5H5jAhwBkDXn:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/4d076c16f9e7e7e7197cbb6e881102f2f681e88d/ops/utils.py#L108)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> of panelapp_id
> ```
of GMS panels panelapp_id
(for consistency with docstrings of related functions)
</blockquote></details>

Done.
___
*[ops/utils.py, line 187 at r4](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MUTZMLU-i56OLVkd2-d:-MVLMoTv-3yJQnuRR-Lh:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/4d076c16f9e7e7e7197cbb6e881102f2f681e88d/ops/utils.py#L187)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
>             gene, transcript = line.strip().split()
>             g2t[gene] = transcript
> ```
Could we add a quick check to avoid overwriting existing values in the dict if the same gene is present twice in g2t? Would be better to just error/fail
e.g.
```
GeneA  NM_00001.1
GeneA  NM_00002.2
```
</blockquote></details>

Done.
___
*[ops/utils.py, line 199 at r4](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MUT_2wuBo3yAAVaH-o0:-MVLMpOc1OkVbkRfY5Uf:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/4d076c16f9e7e7e7197cbb6e881102f2f681e88d/ops/utils.py#L199)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> file
> ```
filepath
</blockquote></details>

Done.
___
*[ops/utils.py, line 325 at r4](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MUTaWq29BE_m-GFLR3b:-MVLMrFA1-5Dhsnc2UTl:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/4d076c16f9e7e7e7197cbb6e881102f2f681e88d/ops/utils.py#L325)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
>     if gene_symbol in hgnc_data:
>         hgnc_id = hgnc_data[gene_symbol]["hgnc_id"]
>         ensg_id = hgnc_data[gene_symbol]["ensg_id"]
>     elif gene_symbol in alias_data:
>         hgnc_id = alias_data[gene_symbol]["hgnc_id"]
>         ensg_id = alias_data[gene_symbol]["ensg_id"]
>     elif gene_symbol in prev_data:
>         hgnc_id = prev_data[gene_symbol]["hgnc_id"]
>         ensg_id = prev_data[gene_symbol]["ensg_id"]
> ```
If the query symbol is in multiple data (hgnc/alias/prev) can you be certain that you are selecting the intended symbol?
</blockquote></details>

Done.
___
*[ops/utils.py, line 426 at r5](https://reviewable.io/reviews/eastgenomics/panel_ops/27#-MUwHprqBo7ketU4Xo9X:-MVLMrpR0duWihKz3Omt:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/1405f0e957eb1da3a36101d436f6f5bbd5a46dea/ops/utils.py#L426)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
>     return [
>         i
>         for i, ele in enumerate(headers)
>         if ele == header_name
>     ][0]
> ```
or headers.index(header_name)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-10 13:41 UTC, mattgarner approved these changes
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/27)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)



<!-- Sent from Reviewable.io -->

2021-03-10 14:03 UTC, merged