v1.0.0 main.py
eastgenomics/panel_ops pull request #3
Opened 2020-11-24 16:51 UTC by Yu-jinKim

- Call functions for:
    - generating:
         - panelapp dump
         - django json
         - sql dumps
         - sample2panels
    - check:
        - gene transcript
        - db integrity for test + panels
    - query:
        - genes in panel
        - gemini name of a panel
    - mod_db when it'll be ready

2020-11-24 16:51 UTC, pep8speaks commented
Hello @Yu-jinKim! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`main.py`](https://github.com/eastgenomics/panel_ops/blob/e8c433ee28548fa82b89af1ca3a1a52cba622c75/main.py):

> [Line 10:1](https://github.com/eastgenomics/panel_ops/blob/e8c433ee28548fa82b89af1ca3a1a52cba622c75/main.py#L10): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file

2020-11-25 09:32 UTC, jethror1 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/3)* status: 0 of 1 files reviewed, 13 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

*[a discussion](https://reviewable.io/reviews/eastgenomics/panel_ops/3#-MMyga2z3Rpui0WnGV7a:-MMyga3-0QTHqE3fQNjJ:b5sp9cv) (no related file):*
your requirements and readme aren't in either of the PRs, probably would be best in with this

---
___
*[main.py, line 2 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/3#-MMyen6w3Bcyctj4zaWP:-MMyen6w3Bcyctj4zaWQ:b-gammtp) ([raw file](https://github.com/eastgenomics/panel_ops/blob/e8c433ee28548fa82b89af1ca3a1a52cba622c75/main.py#L2)):*
> ```Python
> #!/usr/bin/python3
> ```

doc string to explain what each sub parser does would be useful
___
*[main.py, line 8 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/3#-MMydIg126kBRs0dJrok:-MMydIg126kBRs0dJrol:b-lx3ygb) ([raw file](https://github.com/eastgenomics/panel_ops/blob/e8c433ee28548fa82b89af1ca3a1a52cba622c75/main.py#L8)):*
> ```Python
> import ops
> 
> sys.path.append("/home/egg-user/panels/panel_config")
> ```

could this be included in the same dir and not need a hard coded path? Is this path going to change when it moves from being on the laptop / will this be used elsewhere?
___
*[main.py, line 19 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/3#-MMyhB8UCAk6ch1K_aFS:-MMyhB8UCAk6ch1K_aFT:b-95ohv0) ([raw file](https://github.com/eastgenomics/panel_ops/blob/e8c433ee28548fa82b89af1ca3a1a52cba622c75/main.py#L19)):*
> ```Python
>     test2targets = ops.utils.clean_targets(ci_dict, test_dict)
> 
>     user = config_panel_db.user_admin
> ```

related to above, will this be needed to be used by anyone other than admin (i.e give people access without full write access) and therefore need to pass their own credentials
___
*[main.py, line 71 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/3#-MMyfx0d743MArXnQvvP:-MMyfx0d743MArXnQvvQ:b-vigata) ([raw file](https://github.com/eastgenomics/panel_ops/blob/e8c433ee28548fa82b89af1ca3a1a52cba622c75/main.py#L71)):*
> ```Python
>             )
> 
>         if param["manifest"]:
> ```

comment for what function does
___
*[main.py, line 77 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/3#-MMyg-uT8gP3Px7qeuWt:-MMyg-uUCsuwa5E-7BeI:b-vigata) ([raw file](https://github.com/eastgenomics/panel_ops/blob/e8c433ee28548fa82b89af1ca3a1a52cba622c75/main.py#L77)):*
> ```Python
>             )
> 
>         if param["panel_names_gms"]:
> ```

comment for what function does
___
*[main.py, line 83 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/3#-MMyg0Tk7peCLEcaVkd6:-MMyg0Tk7peCLEcaVkd7:b-vigata) ([raw file](https://github.com/eastgenomics/panel_ops/blob/e8c433ee28548fa82b89af1ca3a1a52cba622c75/main.py#L83)):*
> ```Python
>             )
> 
>         if param["panel_names_all"]:
> ```

comment for what function does
___
*[main.py, line 89 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/3#-MMyhgI07GcfcmEPrBZH:-MMyhgI07GcfcmEPrBZI:b55uis0) ([raw file](https://github.com/eastgenomics/panel_ops/blob/e8c433ee28548fa82b89af1ca3a1a52cba622c75/main.py#L89)):*
> ```Python
>             )
> 
>         # Generate django fixture using given panelapp dump
> ```

might be useful to explain how the dict relates to the db and what the django fixture is
___
*[main.py, line 92 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/3#-MMyg8JG9zGIjMy0ih3Y:-MMyg8JG9zGIjMy0ih3Z:b-cczwe8) ([raw file](https://github.com/eastgenomics/panel_ops/blob/e8c433ee28548fa82b89af1ca3a1a52cba622c75/main.py#L92)):*
> ```Python
>         if param["json"]:
>             pk_dict = {
>                 "test": 1, "panel": 1, "reference": 1,
> ```

why are some 1 and some 0?
___
*[main.py, line 117 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/3#-MMyglPz1b45OPCjwwDR:-MMyglPz1b45OPCjwwDS:b-7r9mwc) ([raw file](https://github.com/eastgenomics/panel_ops/blob/e8c433ee28548fa82b89af1ca3a1a52cba622c75/main.py#L117)):*
> ```Python
>             ops.generate.generate_genepanels(session, meta)
> 
>         # Generate gemini name file from database
> ```

gemini name file?
___
*[main.py, line 124 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/3#-MMygtzS6fLLcVUFk72z:-MMygtzS6fLLcVUFk73-:b-aadxa8) ([raw file](https://github.com/eastgenomics/panel_ops/blob/e8c433ee28548fa82b89af1ca3a1a52cba622c75/main.py#L124)):*
> ```Python
>     elif param["command"] == "query":
>         session, meta = ops.utils.connect_to_db(user, passwd, host)
> ```

comments for these functions
___
*[main.py, line 132 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/3#-MMyiLOI8rW8PnsmMFdW:-MMyiLOI8rW8PnsmMFdX:bafar7r) ([raw file](https://github.com/eastgenomics/panel_ops/blob/e8c433ee28548fa82b89af1ca3a1a52cba622c75/main.py#L132)):*
> ```Python
>             )
> 
>     elif param["command"] == "mod_db":
> ```

is this working / will be with this release? If not I don't think it should be in here yet since if it doesn't have the expected functionality
___
*[main.py, line 136 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/3#-MMygy_zEIb8x4VsL_vk:-MMygy_zEIb8x4VsL_vl:bq8afp5) ([raw file](https://github.com/eastgenomics/panel_ops/blob/e8c433ee28548fa82b89af1ca3a1a52cba622c75/main.py#L136)):*
> ```Python
>             ops.mod_db.import_django_fixture(
>                 param["initial_import"]
>             )
> ```

comments


<!-- Sent from Reviewable.io -->

2020-12-03 11:04 UTC, Yu-jinKim reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/3)* status: 0 of 1 files reviewed, 13 unresolved discussions (waiting on @jethror1)

*[a discussion](https://reviewable.io/reviews/eastgenomics/panel_ops/3#-MMyga2z3Rpui0WnGV7a:-MNcGdgH-KabJUcS52R9:b-896fix) (no related file):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

your requirements and readme aren't in either of the PRs, probably would be best in with this
</blockquote></details>

Done.

---
___
*[main.py, line 2 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/3#-MMyen6w3Bcyctj4zaWP:-MNcGP9k4wDwFYVSS0GP:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/e8c433ee28548fa82b89af1ca3a1a52cba622c75/main.py#L2)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

doc string to explain what each sub parser does would be useful
</blockquote></details>

Done.
___
*[main.py, line 8 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/3#-MMydIg126kBRs0dJrok:-MNcGPsLC0nKQ7dCSOdl:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/e8c433ee28548fa82b89af1ca3a1a52cba622c75/main.py#L8)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

could this be included in the same dir and not need a hard coded path? Is this path going to change when it moves from being on the laptop / will this be used elsewhere?
</blockquote></details>

Done.
___
*[main.py, line 19 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/3#-MMyhB8UCAk6ch1K_aFS:-MNcELy_BP822noxg8A_:b-4vt7p7) ([raw file](https://github.com/eastgenomics/panel_ops/blob/e8c433ee28548fa82b89af1ca3a1a52cba622c75/main.py#L19)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

related to above, will this be needed to be used by anyone other than admin (i.e give people access without full write access) and therefore need to pass their own credentials
</blockquote></details>

Might be something to discuss about, I'm not sure how to handle that for now
___
*[main.py, line 71 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/3#-MMyfx0d743MArXnQvvP:-MNcGQfu5ANaes0cjkQU:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/e8c433ee28548fa82b89af1ca3a1a52cba622c75/main.py#L71)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

comment for what function does
</blockquote></details>

Done.
___
*[main.py, line 77 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/3#-MMyg-uT8gP3Px7qeuWt:-MNcGRCH1BpOIgfHnMFY:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/e8c433ee28548fa82b89af1ca3a1a52cba622c75/main.py#L77)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

comment for what function does
</blockquote></details>

Done.
___
*[main.py, line 83 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/3#-MMyg0Tk7peCLEcaVkd6:-MNcGReB5ChILIFgqSqh:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/e8c433ee28548fa82b89af1ca3a1a52cba622c75/main.py#L83)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

comment for what function does
</blockquote></details>

Done.
___
*[main.py, line 89 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/3#-MMyhgI07GcfcmEPrBZH:-MNcGS0G5LmoS1aLDzTm:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/e8c433ee28548fa82b89af1ca3a1a52cba622c75/main.py#L89)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

might be useful to explain how the dict relates to the db and what the django fixture is
</blockquote></details>

Done.
___
*[main.py, line 92 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/3#-MMyg8JG9zGIjMy0ih3Y:-MNcGSUnD1cVoi7Ej1SU:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/e8c433ee28548fa82b89af1ca3a1a52cba622c75/main.py#L92)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

why are some 1 and some 0?
</blockquote></details>

Done.
___
*[main.py, line 117 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/3#-MMyglPz1b45OPCjwwDR:-MNcGT7M0Ijy_8Q70YOB:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/e8c433ee28548fa82b89af1ca3a1a52cba622c75/main.py#L117)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

gemini name file?
</blockquote></details>

Done.
___
*[main.py, line 124 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/3#-MMygtzS6fLLcVUFk72z:-MNcGTeX2Z_MA5qRywn6:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/e8c433ee28548fa82b89af1ca3a1a52cba622c75/main.py#L124)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

comments for these functions
</blockquote></details>

Done.
___
*[main.py, line 132 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/3#-MMyiLOI8rW8PnsmMFdW:-MNcGUkrBKkkSZ9asn8f:b-mtmv5i) ([raw file](https://github.com/eastgenomics/panel_ops/blob/e8c433ee28548fa82b89af1ca3a1a52cba622c75/main.py#L132)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

is this working / will be with this release? If not I don't think it should be in here yet since if it doesn't have the expected functionality
</blockquote></details>

The initial part will be there for the initial release, i removed the updating bit
___
*[main.py, line 136 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/3#-MMygy_zEIb8x4VsL_vk:-MNcGVJrC0voFAvBoCI7:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/e8c433ee28548fa82b89af1ca3a1a52cba622c75/main.py#L136)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

comments
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-03 11:20 UTC, jethror1 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/3)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[main.py, line 19 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/3#-MMyhB8UCAk6ch1K_aFS:-MNcJwPr3_yk12uJtMLe:bj36hc9) ([raw file](https://github.com/eastgenomics/panel_ops/blob/e8c433ee28548fa82b89af1ca3a1a52cba622c75/main.py#L19)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

Might be something to discuss about, I'm not sure how to handle that for now
</blockquote></details>

a question for @mattgarner ?


<!-- Sent from Reviewable.io -->

2021-01-20 22:17 UTC, closed without merging