v1.0.0 utils.py
eastgenomics/panel_ops pull request #4
Opened 2020-11-24 17:02 UTC by Yu-jinKim

- assign_transcript
- get_date
- connect_to_db
- get_all_panels
- parse_HGMD
- get_nirvana_data_dict
- create_panelapp_dict
- parse_tests_xls
- clean_targets
- parse_coor
- parse_gemini_dump

2020-11-24 17:02 UTC, pep8speaks commented
Hello @Yu-jinKim! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`ops/utils.py`](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py):

> [Line 177:80](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L177): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (91 > 79 characters)
> [Line 185:80](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L185): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (92 > 79 characters)
> [Line 212:80](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L212): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (111 > 79 characters)
> [Line 231:80](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L231): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 232:80](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L232): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 233:80](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L233): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 253:80](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L253): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 261:80](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L261): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 262:80](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L262): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 265:80](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L265): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 266:80](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L266): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (102 > 79 characters)
> [Line 267:80](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L267): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (102 > 79 characters)
> [Line 268:80](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L268): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (98 > 79 characters)
> [Line 269:80](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L269): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (90 > 79 characters)
> [Line 284:80](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L284): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 285:80](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L285): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (91 > 79 characters)
> [Line 291:80](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L291): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (98 > 79 characters)
> [Line 297:80](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L297): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (98 > 79 characters)
> [Line 314:80](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L314): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (98 > 79 characters)
> [Line 320:80](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L320): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (98 > 79 characters)
> [Line 419:80](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L419): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)

2020-11-24 21:47 UTC, jethror1 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/4)* status: 0 of 1 files reviewed, 13 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[ops/utils.py, line 9 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/4#-MMw5ahz-N2vycwOZgYr:-MMw5ahz-N2vycwOZgYs:b2lpcrv) ([raw file](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L9)):*
> ```Python
> import regex
> import sqlalchemy
> from sqlalchemy.orm import sessionmaker
> ```

importing sqlalchemy and separate functions, is the `import sqlalchemy` required?
___
*[ops/utils.py, line 38 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/4#-MMw5rd_6XGRvzemnt7j:-MMw5rd_6XGRvzemnt7k:b-fuc82) ([raw file](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L38)):*
> ```Python
>         if uppered_gene in nirvana_dict:
>             transcript_data = nirvana_dict[uppered_gene]
>             hgmd_tx = hgmd_dict[uppered_gene]
> ```

will keys in both these dicts always be upper case?
___
*[ops/utils.py, line 74 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/4#-MMw6oYSBIz4y0oYI7PH:-MMw6oYSBIz4y0oYI7PI:bdjmgjz) ([raw file](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L74)):*
> ```Python
>     """
> 
>     db = sqlalchemy.create_engine(
> ```

does this require try except in event of failing to connect?
___
*[ops/utils.py, line 80 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/4#-MMw6vugAjTqk3ZnZ08v:-MMw6vugAjTqk3ZnZ08w:b-39jvbi) ([raw file](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L80)):*
> ```Python
>     meta.reflect(bind=db)
>     Session = sessionmaker(bind=db)
>     session = Session()
> ```

ws before return
___
*[ops/utils.py, line 120 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/4#-MMw78DYDoz8gueVEz7t:-MMw78DYDoz8gueVEz7u:b-lml9rg) ([raw file](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L120)):*
> ```Python
> 
>     f = vcf.Reader(dxpy.DXFile(
>         dxid="file-Fv1X0jQ40qBjj4GPKj196kjJ",
> ```

should these be hardcoded or in a config?
___
*[ops/utils.py, line 125 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/4#-MMw7VTKCET2rpaZrrd7:-MMw7VTKCET2rpaZrrd8:b-4vkex6) ([raw file](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L125)):*
> ```Python
> 
>     for line in f:
>         gene = line.INFO["GENE"]
> ```

are you sure these are _always_ present in INFO? HGMD Pro VCF does not consistently have all fields but not sure exactly what you're using here, if you need it this is how I have handled it: https://github.com/NHS-NGS/JellyPy/blob/annoTier/annotier/bin/hgmd_query.py (line 82 onwards)
___
*[ops/utils.py, line 148 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/4#-MMw8cno-v00iXzOzZDB:-MMw8cno-v00iXzOzZDC:b-99xd70) ([raw file](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L148)):*
> ```Python
>     with gzip.open(nirvana_refseq) as nir_fh:
>         for line in nir_fh:
>             fields = line.decode("utf-8").strip().split("\t")
> ```

any chance refseq file will have any funky characters that utf-8 doesn't handle?
___
*[ops/utils.py, line 156 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/4#-MMw8qAYBpzgtKsf1982:-MMw8qAYBpzgtKsf1983:b-6g3ge8) ([raw file](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L156)):*
> ```Python
> 
>             if record_type in ["gene", "UTR", "CDS"]:
>                 continue
> ```

is this meant to have an else to handle if record type isn't in gene, UT or CDS?
___
*[ops/utils.py, line 161 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/4#-MMw9eQ0AbF8UwplJGXf:-MMw9eQ0AbF8UwplJGXg:b7xvuqx) ([raw file](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L161)):*
> ```Python
>                 key, value = field.split(" ")
>                 value = value.strip("\"")
>                 value = value.strip("\'")
> ```

can be one line: `value = value.strip("\'\"")`
___
*[ops/utils.py, line 321 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/4#-MMwBOOw-NVT20Dotx2C:-MMwBOOw-NVT20Dotx2D:bt2gj7j) ([raw file](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L321)):*
> ```Python
>                             cnv_dict[name]["grch38"] = extracted_grch38
>                             region_dict[chrom]["GRCh38"][(extracted_grch38[1:])] = region_check_38
> ```

is there chance of entity type being something other than what is listed or should this be caught in the check above?
___
*[ops/utils.py, line 338 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/4#-MMwBfdjDFplvRm_LJce:-MMwBfdjDFplvRm_LJcf:bx5vvmv) ([raw file](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L338)):*
> ```Python
>     """
> 
>     ci_id2ci = {}
> ```

interesting variable naming, what is it?
___
*[ops/utils.py, line 446 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/4#-MMwCa1OElRRbdniMyIQ:-MMwCa1OElRRbdniMyIR:bnwqfg8) ([raw file](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L446)):*
> ```Python
>             chrom, None, None
>         )
>         region_check = None
> ```

what is the purpose of region check if it can only be None or False
___
*[ops/utils.py, line 464 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/4#-MMwCjqL-kyKhu55YAXi:-MMwCjqL-kyKhu55YAXj:b-kwhktu) ([raw file](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L464)):*
> ```Python
> 
>     # windows encoding otherwise it breaks
>     with open(gemini_dump, encoding="cp1252") as f:
> ```

is this to handle whatever that random character encoding was?


<!-- Sent from Reviewable.io -->

2020-12-01 12:03 UTC, jethror1 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/4)* status: 0 of 1 files reviewed, 13 unresolved discussions (waiting on @Yu-jinKim)

___
*[ops/utils.py, line 45 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/4#-MNTAdTo0mQpD6onrAS_:-MNTAdTpBIgaG5xzoUnY:b5ahj2r) ([raw file](https://github.com/eastgenomics/panel_ops/blob/6396e60fd63730b83c0a752f5fc7b3d50e7706e2/ops/utils.py#L45)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>             else:
>                 for transcript in transcript_data:
>                     if transcript_data[transcript]["canonical"]:
>                         clinical_transcript = transcript
> ```
</details>


This is caught by the if in nirvana_dict below, doesn't need to be here in the else?


<!-- Sent from Reviewable.io -->

2020-12-03 11:32 UTC, Yu-jinKim reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/4)* status: 0 of 1 files reviewed, 13 unresolved discussions (waiting on @jethror1)

___
*[ops/utils.py, line 9 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/4#-MMw5ahz-N2vycwOZgYr:-MNcGph3Bntn2yKcYePW:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L9)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

importing sqlalchemy and separate functions, is the `import sqlalchemy required`?
</blockquote></details>

Done.
___
*[ops/utils.py, line 38 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/4#-MMw5rd_6XGRvzemnt7j:-MNcGrOWAqe-_fLExWYx:bq8h0o2) ([raw file](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L38)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

will keys in both these dicts always be upper case?
</blockquote></details>

The dicts are generated in the script so yes
___
*[ops/utils.py, line 74 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/4#-MMw6oYSBIz4y0oYI7PH:-MNcH1Aq5983zsHr9s7v:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L74)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

does this require try except in event of failing to connect?
</blockquote></details>

Done.
___
*[ops/utils.py, line 80 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/4#-MMw6vugAjTqk3ZnZ08v:-MNcH2eYC6ChU34yJ61B:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L80)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

ws before return
</blockquote></details>

Done.
___
*[ops/utils.py, line 120 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/4#-MMw78DYDoz8gueVEz7t:-MNcH3bJDPIke8xmbiwY:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L120)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

should these be hardcoded or in a config?
</blockquote></details>

Done.
___
*[ops/utils.py, line 125 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/4#-MMw7VTKCET2rpaZrrd7:-MNcIx072A3vkWKxOTec:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L125)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

are you sure these are _always_ present in INFO? HGMD Pro VCF does not consistently have all fields but not sure exactly what you're using here, if you need it this is how I have handled it: https://github.com/NHS-NGS/JellyPy/blob/annoTier/annotier/bin/hgmd_query.py (line 82 onwards)
</blockquote></details>

Done.
___
*[ops/utils.py, line 148 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/4#-MMw8cno-v00iXzOzZDB:-MNcJcj6A3JCqevUZXa6:bb710yj) ([raw file](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L148)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

any chance refseq file will have any funky characters that utf-8 doesn't handle?
</blockquote></details>

Nope
___
*[ops/utils.py, line 156 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/4#-MMw8qAYBpzgtKsf1982:-MNcJkATCCXunlQU5-Aq:b-kss50a) ([raw file](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L156)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

is this meant to have an else to handle if record type isn't in gene, UT or CDS?
</blockquote></details>

nope just skip lines with gene utr or cds
___
*[ops/utils.py, line 161 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/4#-MMw9eQ0AbF8UwplJGXf:-MNcMexxEbDXVLMFvr3i:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L161)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

can be one line: `value = value.strip("\'\"")`
</blockquote></details>

Done.
___
*[ops/utils.py, line 321 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/4#-MMwBOOw-NVT20Dotx2C:-MNcMgef3pZvoBa3JfyF:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L321)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

is there chance of entity type being something other than what is listed or should this be caught in the check above?
</blockquote></details>

Done.
___
*[ops/utils.py, line 338 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/4#-MMwBfdjDFplvRm_LJce:-MNcMh7qAjmENsu8pGDi:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L338)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

interesting variable naming, what is it?
</blockquote></details>

Done.
___
*[ops/utils.py, line 446 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/4#-MMwCa1OElRRbdniMyIQ:-MNcMj1p2bi4kW97S3tp:bamq5ni) ([raw file](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L446)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

what is the purpose of region check if it can only be None or False
</blockquote></details>

Handled create_panelapp_dict
___
*[ops/utils.py, line 464 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/4#-MMwCjqL-kyKhu55YAXi:-MNcMt2V2j0_jwjgmWI3:b2nign6) ([raw file](https://github.com/eastgenomics/panel_ops/blob/07725204c1c64b5a6fd7a81e22baaa9a10a9448b/ops/utils.py#L464)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

is this to handle whatever that random character encoding was?
</blockquote></details>

yes
___
*[ops/utils.py, line 45 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/4#-MNTAdTo0mQpD6onrAS_:-MNcGx5YB_CsdwCZXRyO:bymszr5) ([raw file](https://github.com/eastgenomics/panel_ops/blob/6396e60fd63730b83c0a752f5fc7b3d50e7706e2/ops/utils.py#L45)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

> ```
>             else:
>                 for transcript in transcript_data:
>                     if transcript_data[transcript]["canonical"]:
>                         clinical_transcript = transcript
> ```

This is caught by the if in nirvana_dict below, doesn't need to be here in the else?

</blockquote></details>

No the clinical transcript and transcript_data are None at the beginning


<!-- Sent from Reviewable.io -->

2021-01-20 22:17 UTC, closed without merging