V1.2.0
eastgenomics/panel_ops pull request #46
Opened 2021-06-22 12:38 UTC by Yu-jinKim

- adjust initial importing using dumps to match new panel palace structure (version in clinical indication panels table)
- import bespoke panels

2021-06-22 12:38 UTC, pep8speaks commented
Hello @Yu-jinKim! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`main.py`](https://github.com/eastgenomics/panel_ops/blob/7c50005da89a10847dfb304ed15625549d1ac0d9/main.py):

> [Line 251:1](https://github.com/eastgenomics/panel_ops/blob/7c50005da89a10847dfb304ed15625549d1ac0d9/main.py#L251): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

* In the file [`ops/mod_db.py`](https://github.com/eastgenomics/panel_ops/blob/7c50005da89a10847dfb304ed15625549d1ac0d9/ops/mod_db.py):

> [Line 19:1](https://github.com/eastgenomics/panel_ops/blob/7c50005da89a10847dfb304ed15625549d1ac0d9/ops/mod_db.py#L19): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file

* In the file [`ops/utils.py`](https://github.com/eastgenomics/panel_ops/blob/7c50005da89a10847dfb304ed15625549d1ac0d9/ops/utils.py):

> [Line 1266:80](https://github.com/eastgenomics/panel_ops/blob/7c50005da89a10847dfb304ed15625549d1ac0d9/ops/utils.py#L1266): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)

2021-06-23 17:02 UTC, mattgarner requested changes
> Reviewed 4 of 5 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/46)* status: all files reviewed, 1 unresolved discussion (waiting on @Yu-jinKim)

___
*[main.py, line 251 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/46#-MctQn174KWI4LqI9oqv:-MctQn174KWI4LqI9oqw:b-24jlvk) ([raw file](https://github.com/eastgenomics/panel_ops/blob/0b4cb4b39dd73dbc1b18cee9bfe35e441f327311/main.py#L251)):*
> ```
> ············
> ```
whitespace


<!-- Sent from Reviewable.io -->

2021-06-24 08:27 UTC, Yu-jinKim reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/46)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @mattgarner)

___
*[main.py, line 251 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/46#-MctQn174KWI4LqI9oqv:-Mcx7GLx5fvo0jlPTKVn:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/0b4cb4b39dd73dbc1b18cee9bfe35e441f327311/main.py#L251)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> ············
> ```
whitespace
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-24 12:00 UTC, mattgarner approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/46)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)



<!-- Sent from Reviewable.io -->

2021-06-24 12:00 UTC, merged