V1.4.0
eastgenomics/panel_ops pull request #58
Opened 2022-01-24 12:31 UTC by Yu-jinKim

- handle add on panels
- get latest panel version function
- validate panel form function
- check if data in database function works correctly

2022-01-24 12:31 UTC, pep8speaks commented
Hello @Yu-jinKim! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`ops/mod_db.py`](https://github.com/eastgenomics/panel_ops/blob/fe5151b6f80caebf2c4a3914c8929d1f7761bf19/ops/mod_db.py):

> [Line 251:80](https://github.com/eastgenomics/panel_ops/blob/fe5151b6f80caebf2c4a3914c8929d1f7761bf19/ops/mod_db.py#L251): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)

2022-02-02 07:58 UTC, mattgarner requested changes
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/58)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @mattgarner and @Yu-jinKim)

___
*[ops/check.py, line 74 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/58#-MutOHh18ZyWwFdM2hAE:-MutOHh18ZyWwFdM2hAF:bwzribb) ([raw file](https://github.com/eastgenomics/panel_ops/blob/5152b66833d5a451b3f47125d1c7692a146fbd51/ops/check.py#L74)):*
> ```Python
>     if global_panel_errors is not None:
>         error_detected = True
>         CHECK.error(error)
> ```

Without the `for error in ...` line which has been removed, where is the `error` that's referenced here defined?



_Code quote:_
```Python
error
```


<!-- Sent from Reviewable.io -->

2022-02-02 09:39 UTC, Yu-jinKim reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/58)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @mattgarner)

___
*[ops/check.py, line 74 at r2](https://reviewable.io/reviews/eastgenomics/panel_ops/58#-MutOHh18ZyWwFdM2hAE:-MutnNmI1_UHqWUHUz7W:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/5152b66833d5a451b3f47125d1c7692a146fbd51/ops/check.py#L74)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Without the `for error in ...` line which has been removed, where is the `error` that's referenced here defined?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-02 10:58 UTC, mattgarner approved these changes
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/58)* status: all files reviewed, 1 unresolved discussion (waiting on @Yu-jinKim)

*[a discussion](https://reviewable.io/reviews/eastgenomics/panel_ops/58#-Muu4Lx1BtL-QbDSHp3U:-Muu4Lx1BtL-QbDSHp3V:b-rjqzq1) (no related file):*
Reviewed together on call 220202

---


<!-- Sent from Reviewable.io -->

2022-02-02 10:58 UTC, merged