v1.0.0_mod_db
eastgenomics/panel_ops pull request #7
Opened 2020-11-30 15:20 UTC by Yu-jinKim

- function import data in the database

2020-11-30 15:21 UTC, pep8speaks commented
Hello @Yu-jinKim! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`ops/mod_db.py`](https://github.com/eastgenomics/panel_ops/blob/ab3d3aa32049bed5cb1e5fa938cdfcb3a7d54edc/ops/mod_db.py):

> [Line 12:1](https://github.com/eastgenomics/panel_ops/blob/ab3d3aa32049bed5cb1e5fa938cdfcb3a7d54edc/ops/mod_db.py#L12): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 13:1](https://github.com/eastgenomics/panel_ops/blob/ab3d3aa32049bed5cb1e5fa938cdfcb3a7d54edc/ops/mod_db.py#L13): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 20:80](https://github.com/eastgenomics/panel_ops/blob/ab3d3aa32049bed5cb1e5fa938cdfcb3a7d54edc/ops/mod_db.py#L20): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)

2020-12-01 14:12 UTC, jethror1 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/7)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[ops/mod_db.py, line 1 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/7#-MNTd-RFA7dPczjb5Fq_:-MNTd-RG4ut2dCbb03Gz:b-q00j8c) ([raw file](https://github.com/eastgenomics/panel_ops/blob/ab3d3aa32049bed5cb1e5fa938cdfcb3a7d54edc/ops/mod_db.py#L1)):*
> ```Python
> import os
> ```

doc string for script
___
*[ops/mod_db.py, line 8 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/7#-MNTd0uyBOoB5X7mxyYk:-MNTd0uyBOoB5X7mxyYl:b-e8hrh5) ([raw file](https://github.com/eastgenomics/panel_ops/blob/ab3d3aa32049bed5cb1e5fa938cdfcb3a7d54edc/ops/mod_db.py#L8)):*
> ```Python
> from .logger import setup_logging
> 
> sys.path.append('/home/egg-user/panels/panel_palace/')
> ```

should this be either passed or in config?
___
*[ops/mod_db.py, line 12 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/7#-MNTd83w-6Z9gf4v4SUF:-MNTd83w-6Z9gf4v4SUG:b94cvim) ([raw file](https://github.com/eastgenomics/panel_ops/blob/ab3d3aa32049bed5cb1e5fa938cdfcb3a7d54edc/ops/mod_db.py#L12)):*
> ```Python
> django.setup()
> 
> from django.core import management
> ```

should these not be at the top with import django, or do they need to be after setdefault?
___
*[ops/mod_db.py, line 32 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/7#-MNTdPbC8D7-XH8sgK5f:-MNTdPbC8D7-XH8sgK5g:bxgtqsj) ([raw file](https://github.com/eastgenomics/panel_ops/blob/ab3d3aa32049bed5cb1e5fa938cdfcb3a7d54edc/ops/mod_db.py#L32)):*
> ```Python
> 
>     try:
>         management.call_command(loaddata.Command(), path_to_json)
> ```

maybe a comment to say what this does?


<!-- Sent from Reviewable.io -->

2020-12-03 11:38 UTC, Yu-jinKim reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/7)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @jethror1)

___
*[ops/mod_db.py, line 1 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/7#-MNTd-RFA7dPczjb5Fq_:-MNcNFDC5T_Qw1Gp74o2:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/ab3d3aa32049bed5cb1e5fa938cdfcb3a7d54edc/ops/mod_db.py#L1)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

doc string for script
</blockquote></details>

Done.
___
*[ops/mod_db.py, line 8 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/7#-MNTd0uyBOoB5X7mxyYk:-MNcNFwH4InYzSyQOIZp:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/ab3d3aa32049bed5cb1e5fa938cdfcb3a7d54edc/ops/mod_db.py#L8)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

should this be either passed or in config?
</blockquote></details>

Done.
___
*[ops/mod_db.py, line 12 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/7#-MNTd83w-6Z9gf4v4SUF:-MNcNI0KAuELrDfZI5aw:b-4xpiu0) ([raw file](https://github.com/eastgenomics/panel_ops/blob/ab3d3aa32049bed5cb1e5fa938cdfcb3a7d54edc/ops/mod_db.py#L12)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

should these not be at the top with import django, or do they need to be after setdefault?
</blockquote></details>

after setdefault
___
*[ops/mod_db.py, line 32 at r1](https://reviewable.io/reviews/eastgenomics/panel_ops/7#-MNTdPbC8D7-XH8sgK5f:-MNcONN0BkHF-FQ8gNNt:b-896fix) ([raw file](https://github.com/eastgenomics/panel_ops/blob/ab3d3aa32049bed5cb1e5fa938cdfcb3a7d54edc/ops/mod_db.py#L32)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

maybe a comment to say what this does?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-03 12:09 UTC, jethror1 approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_ops/7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)



<!-- Sent from Reviewable.io -->

2020-12-03 12:10 UTC, merged